version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    groups:
      data:
        patterns:
          - "@webref/*"
      dev:
        exclude-patterns:
          - "@webref/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
